name: Home Assistant Minecraft Server Java
description: Host a Java Minecraft server on Home Assistant
version: 1.0.1-rc4
slug: hamc-java
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  25565/tcp: "25565"
ports_description:
  25565/tcp: Minecraft Server Port
options:
  TYPE: VANILLA
  VERSION: LATEST
  SERVER_NAME: "Home Assistant Minecraft Java Server"
  MOTD: "Greetings from Home Assistant"
  PVP: true
  ALLOW_NETHER: true
  ONLINE_MODE: true
  ANNOUNCE_PLAYER_ACHIEVEMENTS: true
  ENABLE_COMMAND_BLOCK: false
  FORCE_GAMEMODE: false
schema:
  TYPE: str
  VERSION: str
  SERVER_NAME: str
  MOTD: str
  LEVEL: str
  MODE: list(survival|creative|adventure|spectator)?
  DIFFICULTY: list(peaceful|easy|normal|hard)?
  HARDCORE: bool?
  MAX_PLAYERS: int?
  WHITELIST: str?
  OPS: str?
  SPAWN_PROTECTION: int?
  PVP: bool
  MAX_WORLD_SIZE: int?
  ALLOW_NETHER: bool
  SEED: str?
  VIEW_DISTANCE: int?
  ONLINE_MODE: bool
  MEMORY: str?
  ANNOUNCE_PLAYER_ACHIEVEMENTS: bool
  ENABLE_COMMAND_BLOCK: bool
  FORCE_GAMEMODE: bool
  MAX_BUILD_HEIGHT: int?
  CF_API_KEY: str?
  CURSEFORGE_FILES: str?
  EXTRA_ARGS: str?
  EXISTING_WHITELIST_FILE: str?
  EXISTING_OPS_FILE: str?

map:
  - addons:rw
  - addon_config:rw
  - share:rw
environment:
  EULA: "TRUE"
  COPY_PLUGINS_SRC: "/config/plugins"
  COPY_MODS_SRC: "/config/mods"
  COPY_CONFIG_SRC: "/config/config"
